// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwodlxodqrqotxecubjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3b2RseG9kcXJxb3R4ZWN1YmpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMTY0NTUsImV4cCI6MjA1OTc5MjQ1NX0.ZbgmFmb5rop7Glb5ey4XrvbSdIkAiyMXITiyIEagz08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);